[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.49"
enum-map = "1.1.1"
num-bigint = "0.4.3"
rayon = "1.5.1"
smallvec = "1.7.0"
